#!/bin/bash -eu

. debian/debian.env

CONF="${DEBIAN}"/etc/update.conf
if [ -f "${CONF}" ]; then
        # shellcheck disable=SC1090
        . "${CONF}"
fi

# Ovveride default GCC version to the default in Jammy
GCC="gcc-11"

# Override options in rules.d/hooks.mk (normally master does not have this
# file but it got added for generic annotations enforcement.
# Currently there is no hooks.mk in ${DEBIAN_MASTER}/rules.d which creates
# an ever growing hooks.mk. Reset the file if there is no origin.
if [ ! -r "${DEBIAN_MASTER}/rules.d/hooks.mk" ]; then
	rm -f "${DEBIAN}/rules.d/hooks.mk"
	touch "${DEBIAN}/rules.d/hooks.mk"
fi
cat <<EOD >>"${DEBIAN}/rules.d/hooks.mk"
do_libc_dev_package	= false
do_doc_package		= false
do_tools_common		= false
do_tools_host		= false
do_lib_rust		= false
gcc			= $GCC
EOD

