name: zynqmp-kernel
summary: The Xilinx Kernel for ZynqMP SoCs
description: The Xilinx Kernel for ZynqMP SoCs as a snap
grade: devel
confinement: devmode
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    build-for: arm64

build-base: core22
assumes:
  - kernel-assets

parts:
  kernel:
    after:
      - firmware
    plugin: kernel
    source: .
    source-type: local
    kernel-kconfigflavour: "xilinx-zynqmp"
    kernel-with-firmware: false
    kernel-enable-zfs-support: true
    kernel-initrd-compression: lz4
    kernel-initrd-stage-firmware: true
    kernel-initrd-modules:
      - libarc4
      - tpm_tis
      - sbp2
      - usb-storage
      - ehci-hcd
      - uhci-hcd
      - scsi_mod
      - sr_mod
      - sd_mod
      - tls
      - ina260_adc
      - tpm_tis_spi
      - scsi_dh_rdac
      - scsi_dh_emc
      - scsi_dh_alua
      - autofs4
      - rtc_zynqmp
      - spi_zynqmp_gqspi
      - i2c_cadence
      - zynqmp_dpsub
      - xhci_hcd
      - xhci_pci
      - efi_pstoreg
      - ehci_hcdg
      - tpmg
      - tpm_crbg
      - tpm_tisg
      - tpm_tis_coreg
      - xhci_pcig
    kernel-kconfigs:
      - CONFIG_SYSTEM_TRUSTED_KEYS=""
      - CONFIG_SYSTEM_REVOCATION_KEYS=""
    override-build: |
      craftctl default
      kernel_version=$(dpkg-parsechangelog -l ${CRAFT_PART_SRC}/debian.zynqmp/changelog -S version)
      craftctl set version=${kernel_version}
    override-prime: |
      craftctl default
      ${CRAFT_STAGE}/trim-firmware ${CRAFT_PRIME}
    stage:
      - config-*
      - initrd.img
      - kernel.img
      - lib
      - modules
      - System.map-*
      - Image.gz-*
      - dtbs/xilinx/zynqmp-smk-k26-revA.dtb
      - dtbs/xilinx/smk-k26-revA-sck-kr-g-revA.dtb
      - dtbs/xilinx/smk-k26-revA-sck-kv-g-revA.dtb
      - dtbs/xilinx/smk-k26-revA-sck-kr-g-revB.dtb
      - dtbs/xilinx/smk-k26-revA-sck-kv-g-revB.dtb
    prime:
      - -initrd.img
      - -kernel.img
    organize:
      Image.gz-*: Image.gz-5.15

  firmware:
    plugin: dump
    source: https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc22
    source-type: git
    source-branch: main
    stage-packages:
      - linux-firmware
    organize:
      lib/firmware: firmware
    prime:
      - firmware

  mkimage:
    plugin: nil
    after:
      - kernel
      - meta-files
    build-packages:
      - u-boot-tools
      - device-tree-compiler
    override-build:
      mkimage -f ${CRAFT_STAGE}/meta/image-zynqmp.its ${CRAFT_STAGE}/image.fit
    prime:
      - image.fit

  meta-files:
    plugin: nil
    source: meta-files
    override-build: |
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/meta
      cp -a * "$SNAPCRAFT_PART_INSTALL"/meta
    stage:
      - meta/image-zynqmp.its
      - meta/kernel.yaml



build-packages:
    - android-tools-mkbootimg
    - bison
    - cpio
    - dirmngr
    - dpkg-dev
    - flex
    - gcc-aarch64-linux-gnu
    - libelf-dev
