#!/bin/bash -eu

. debian/debian.env

# Do not enforce DMESG_RESTRICT in focal
sed -i 's/CONFIG_SECURITY_DMESG_RESTRICT=y/# CONFIG_SECURITY_DMESG_RESTRICT is not set/' ${DEBIAN}/config/config.common.ubuntu
sed -i "s/CONFIG_SECURITY_DMESG_RESTRICT                  policy<{'riscv64': 'y'}>/CONFIG_SECURITY_DMESG_RESTRICT                  policy<{'riscv64': 'n'}>/" ${DEBIAN}/config/annotations

# Disable DEBUG_INFO_BTF (pahole version is too old in focal)
sed -i 's/CONFIG_DEBUG_INFO_BTF=y/# CONFIG_DEBUG_INFO_BTF is not set/' ${DEBIAN}/config/config.common.ubuntu
sed -i "s/CONFIG_DEBUG_INFO_BTF                           policy<{'riscv64': 'y'}>/CONFIG_DEBUG_INFO_BTF                           policy<{'riscv64': 'n'}>/" ${DEBIAN}/config/annotations

# Enable AUFS
cat << EOF >>${DEBIAN}/config/config.common.ubuntu
CONFIG_AUFS_BDEV_LOOP=y
# CONFIG_AUFS_BRANCH_MAX_1023 is not set
CONFIG_AUFS_BRANCH_MAX_127=y
# CONFIG_AUFS_BRANCH_MAX_32767 is not set
# CONFIG_AUFS_BRANCH_MAX_511 is not set
# CONFIG_AUFS_BR_FUSE is not set
CONFIG_AUFS_BR_HFSPLUS=y
# CONFIG_AUFS_BR_RAMFS is not set
# CONFIG_AUFS_DEBUG is not set
CONFIG_AUFS_DIRREN=y
CONFIG_AUFS_EXPORT=y
# CONFIG_AUFS_FHSM is not set
CONFIG_AUFS_FS=m
# CONFIG_AUFS_HNOTIFY is not set
CONFIG_AUFS_INO_T_64=y
# CONFIG_AUFS_RDU is not set
CONFIG_AUFS_SBILIST=y
# CONFIG_AUFS_SHWH is not set
CONFIG_AUFS_XATTR=y
EOF

TMPFILE=$(mktemp)
cat <<EOF >${TMPFILE} || true
CONFIG_AUFS_BR_FUSE                             policy<{'riscv64': 'n'}>
CONFIG_AUFS_BR_HFSPLUS                          policy<{'riscv64': 'y'}>
CONFIG_AUFS_BR_RAMFS                            policy<{'riscv64': 'n'}>
CONFIG_AUFS_DEBUG                               policy<{'riscv64': 'n'}>
CONFIG_AUFS_DIRREN                              policy<{'riscv64': 'y'}>
CONFIG_AUFS_EXPORT                              policy<{'riscv64': 'y'}>
CONFIG_AUFS_FHSM                                policy<{'riscv64': 'n'}>
CONFIG_AUFS_FS                                  policy<{'riscv64': 'm'}>
CONFIG_AUFS_HNOTIFY                             policy<{'riscv64': 'n'}>
CONFIG_AUFS_RDU                                 policy<{'riscv64': 'n'}>
CONFIG_AUFS_SHWH                                policy<{'riscv64': 'n'}>
CONFIG_AUFS_XATTR                               policy<{'riscv64': 'y'}>
#
CONFIG_AUFS_EXPORT                              note<LP:1121699>
EOF
gawk -i inplace "/CONFIG_AUFS_FS                                  policy<{'riscv64': 'n'}>/{system(\"cat ${TMPFILE}\");next}1" ${DEBIAN}/config/annotations
rm -f ${TMPFILE}

# Override options in rules.d/hooks.mk (normally master does not have this
# file but it got added for generic annotations enforcement.
cat <<EOD >>${DEBIAN}/rules.d/hooks.mk
do_libc_dev_package	= false
do_doc_package		= false
do_tools_common		= false
do_tools_host		= false
EOD
