---
on:
  pull_request_target:
    types:
      - edited
      - opened
      - synchronize

jobs:
  sru-checks:
    uses:  kernel/kernel-ci/.gitea/workflows/sru-kernel.yaml@v1
    with:
      clone_head_url: ${{ github.event.pull_request.head.repo.clone_url }}
      clone_base_url: ${{ github.event.pull_request.base.repo.clone_url }}
      head_ref: ${{ github.event.pull_request.head.ref }}
      base_ref: ${{ github.event.pull_request.base.ref }}
    secrets:
      cbd_user: ${{ secrets.CBD_BOT_USER }}
      cbd_key: ${{ secrets.CBD_BOT_KEY }}
      cbd_host: ${{ secrets.CBD_HOST }}
