#!/bin/bash -eu

. debian/debian.env

# Override config settings (in the annotations) which are not applicable in the
# 22-04/Jammy environment when using GCC-11.
GCC=$(grep "export gcc.=" debian/rules.d/0-common-vars.mk | cut -d= -f2)
GCCV=$(${CHROOT:-} $GCC --version | grep ^gcc | cut -d" " -f3 | cut -d. -f1)

if [ "$GCCV" = "11" ]; then
    if ! grep -q CONFIG_INIT_STACK_ALL_ZERO "${DEBIAN}/config/annotations"
    then
        cat <<EOD >> "${DEBIAN}/config/annotations"
CONFIG_INIT_STACK_ALL_ZERO policy<{'amd64': '-', 'arm64': '-'}
CONFIG_SHADOW_CALL_STACK policy<{'amd64': '-', 'arm64': '-'}
EOD
    fi
fi

# Override options in rules.d/hooks.mk (normally master does not have this
# file but it got added for generic annotations enforcement.
if ! grep -q do_libc_dev_package "${DEBIAN}/rules.d/hooks.mk"
then
cat <<EOD >>"${DEBIAN}/rules.d/hooks.mk"
do_libc_dev_package = false
do_doc_package      = false
do_tools_common     = false
do_tools_host       = false
EOD
fi

