#!/bin/bash -eu

# shellcheck disable=SC1091
. debian/debian.env

# It's not necessary to update "${DEBIAN}/rules.d/*.mk" because
# hooks.mk can be used to override them.

# Update config options and the annotations file.
configs=(
    'CONFIG_AUFS_BDEV_LOOP=y'
    'CONFIG_AUFS_BRANCH_MAX_1023=n'
    'CONFIG_AUFS_BRANCH_MAX_127=y'
    'CONFIG_AUFS_BRANCH_MAX_32767=n'
    'CONFIG_AUFS_BRANCH_MAX_511=n'
    'CONFIG_AUFS_BR_FUSE=n'
    'CONFIG_AUFS_BR_HFSPLUS=y'
    'CONFIG_AUFS_BR_RAMFS=n'
    'CONFIG_AUFS_DEBUG=n'
    'CONFIG_AUFS_DIRREN=y'
    'CONFIG_AUFS_EXPORT=y'
    'CONFIG_AUFS_FHSM=n'
    'CONFIG_AUFS_FS=m'
    'CONFIG_AUFS_HNOTIFY=n'
    'CONFIG_AUFS_INO_T_64=y'
    'CONFIG_AUFS_RDU=n'
    'CONFIG_AUFS_SBILIST=y'
    'CONFIG_AUFS_SHWH=n'
    'CONFIG_AUFS_XATTR=y'
    'CONFIG_DEBUG_INFO_DWARF4=y'
    'CONFIG_DEBUG_INFO_DWARF5=n'
)

# Load archs supported in the configs
archs=
# shellcheck disable=SC2034
variant=
# shellcheck disable=SC1090
. "${DEBIAN}/etc/kernelconfig"

# Configs should be in the common config file
annot_file="${DEBIAN}/config/annotations"
for config in "${configs[@]}"; do
    # Split key and value
    key="${config%%=*}"
    val="${config#*=}"
    # Drop unused archs
    for arch_dir in "${DEBIAN}"/config/*; do
        [ ! -d "$arch_dir" ] && continue
        dir_arch="${arch_dir##*/}"
        skip=0
        for arch in ${archs}; do
            [ "$dir_arch" = "$arch" ] && skip=1
        done
        [ "$skip" -ne 0 ] && continue
        rm -rf "$arch_dir"
    done
    for config_file in "${DEBIAN}/config/config.common.ubuntu" \
                   "${DEBIAN}"/config/*/config.*; do
        # Remove any existing config
        sed -i -e "/^${key}=/d" -e "/^# ${key} /d" "$config_file"
        # Append desirable config value
        echo "${key}=${val:-n}" >> "$config_file"
    done
    # Remove any existing annotations
    sed -i -e "/^${key}\>/d" "$annot_file"
    # Append new annotations
    {
        echo -ne "${key}\tpolicy<{"
        for arch in ${archs}; do
            echo -n "'${arch}': '${val:--}',"
        done
        echo "}>"
        echo -e "${key}\tmark<ENFORCED> note<custom changes>"
    } >> "$annot_file"
done
