// SPDX-License-Identifier: GPL-2.0
/*
 *  fpga.h - QED spi fgpa register definitions.
 *
 *  Copyright (C) 2021 Lantronix Inc.
 *
 */

#ifndef FPGA_H_
#define FPGA_H_

#define FPGA_CFG_SPI_DEV_CFG 1

#define FPGA_CFG_SPI_CS 0

#define FPGA_ID_VALUE 0x56

/* FPGA registers definition */
#define FPGA_ID 0x7f

/* FPGA_CONFIG_MODE */
#define FPGA_CFG_MODE 0x7e

#define FPGA_CFG_MODE_CFG_SPI 0x10

enum fpga_cfg {
        FPGA_CFG_MODE_CFG_NORMAL,
        FPGA_CFG_MODE_CFG_ADC0 = 2,
        FPGA_CFG_MODE_CFG_ADC1,
};

enum fpga_type {
        FPGA_NONE,
        FPGA_INTEL,
        FPGA_LATTICE,
};

struct fpga_pps_dbg {
        int8_t slice_3_err;
        int8_t slice_2_err;
        int8_t slice_1_err;
        int8_t slice_0_err;
        uint8_t freq_err_threshold;
        uint8_t sync_err_threshold;
        int8_t pps_phase_offset;
        int8_t freq_monitor_delta;
};

#define FPGA_CFG_MODE_RESET 0x00

/* FPGA_WINDOWS_SIZE */
#define FPGA_WINDOW_SIZE 0x6f
#define FPGA_WINDOW_RESET 65

/* FPGA_IRQ_OFFSET */
#define FPGA_IRQ_OFFSET 0x6e
#define FPGA_IRQ_OFFSET_RESET 50

/* FPGA_IRQ_MSK_HI */
#define FPGA_IRQ_MSK_HI 0x6d
#define FPGA_IRQ_MSK_HI_DEFAULT 0xff
#define FPGA_IRQ_MSK_HI_CH15 BIT(7)
#define FPGA_IRQ_MSK_HI_CH14 BIT(6)
#define FPGA_IRQ_MSK_HI_CH13 BIT(5)
#define FPGA_IRQ_MSK_HI_CH12 BIT(4)
#define FPGA_IRQ_MSK_HI_CH11 BIT(3)
#define FPGA_IRQ_MSK_HI_CH10 BIT(2)
#define FPGA_IRQ_MSK_HI_CH9 BIT(1)
#define FPGA_IRQ_MSK_HI_CH8 BIT(0)

/* FPGA_IRQ_IRQ_MSK_LOW */
#define FPGA_IRQ_MSK_LOW 0x6c
#define FPGA_IRQ_MSK_LOW_DEFAULT 0xff
#define FPGA_IRQ_MSK_LOW_CH7 BIT(7)
#define FPGA_IRQ_MSK_LOW_CH6 BIT(6)
#define FPGA_IRQ_MSK_LOW_CH5 BIT(5)
#define FPGA_IRQ_MSK_LOW_CH4 BIT(4)
#define FPGA_IRQ_MSK_LOW_CH3 BIT(3)
#define FPGA_IRQ_MSK_LOW_CH2 BIT(2)
#define FPGA_IRQ_MSK_LOW_CH1 BIT(1)
#define FPGA_IRQ_MSK_LOW_CH0 BIT(0)

/* FPGA_TEST_MODE */
#define FPGA_TEST_MODE 0x6b
#define FPGA_TEST_MODE_DEFAULT BIT(4)
#define FPGA_TEST_MODE1 BIT(0)
#define FPGA_TEST_MODE2 BIT(1)
#define FPGA_TEST_MODE_PPS_SET BIT(4)
#define FPGA_TEST_MODE_PPS_UNSET 0x0
#define FPGA_TEST_MODE_PPS_MSK BIT(4)

/* FPGA_STAT */
#define FPGA_STAT 0x6a
#define FPGA_STAT_DEFAULT 0x00
#define FPGA_STAT_FATAL BIT(7)
#define FPGA_STAT_FRQ_ERROR BIT(6)
#define FPGA_STAT_OUT_SYNC BIT(5)
#define FPGA_STAT_UNDERFLOW BIT(4)
#define FPGA_STAT_OVERFLOW BIT(3)
#define FPGA_STAT_WAIT_PPS BIT(0)

#define FPGA_STAT_PLL_LOCK_DEASSERT BIT(2)
#define FPGA_STAT_PLL_LOCK_ASSERT BIT(1)
#define FPGA_STAT_PLL_LOCK BIT(0)

/* FPGA_SOFT_RESET */
#define FPGA_SOFT_RESET 0x69
#define FPGA_SOFT_RESET_MSK BIT(0)
#define FPGA_SOFT_RESET_SLICE_MSK GENMASK(7,4)
#define FPGA_ADC_RESET_MSK BIT(1)
#define FPGA_SOFT_RESET_RELEASE 0
#define FPGA_SOFT_RESET_SET 1
#define FPGA_ADC_RESET_RELEASE 0
#define FPGA_ADC_RESET_SET BIT(1)

/* FPGA_IRQ_HI */
#define FPGA_IRQ_HI 0x68
#define FPGA_IRQ_HI_DEFAULT 0xff
#define FPGA_IRQ_HI_CH15 BIT(7)
#define FPGA_IRQ_HI_CH14 BIT(6)
#define FPGA_IRQ_HI_CH13 BIT(5)
#define FPGA_IRQ_HI_CH12 BIT(4)
#define FPGA_IRQ_HI_CH11 BIT(3)
#define FPGA_IRQ_HI_CH10 BIT(2)
#define FPGA_IRQ_HI_CH9 BIT(1)
#define FPGA_IRQ_HI_CH8 BIT(0)

/* FPGA_IRQ_LOW */
#define FPGA_IRQ_LOW 0x67
#define FPGA_IRQ_LOW_DEFAULT 0xff
#define FPGA_IRQ_LOW_CH7 BIT(7)
#define FPGA_IRQ_LOW_CH6 BIT(6)
#define FPGA_IRQ_LOW_CH5 BIT(5)
#define FPGA_IRQ_LOW_CH4 BIT(4)
#define FPGA_IRQ_LOW_CH3 BIT(3)
#define FPGA_IRQ_LOW_CH2 BIT(2)
#define FPGA_IRQ_LOW_CH1 BIT(1)
#define FPGA_IRQ_LOW_CH0 BIT(0)

/* FPGA_OVERFLOW_HI */
#define FPGA_OVERFLOW_HI 0x66
#define FPGA_OVERFLOW_HI_DEFAULT 0xff
#define FPGA_OVERFLOW_HI_CH15 BIT(7)
#define FPGA_OVERFLOW_HI_CH14 BIT(6)
#define FPGA_OVERFLOW_HI_CH13 BIT(5)
#define FPGA_OVERFLOW_HI_CH12 BIT(4)
#define FPGA_OVERFLOW_HI_CH11 BIT(3)
#define FPGA_OVERFLOW_HI_CH10 BIT(2)
#define FPGA_OVERFLOW_HI_CH9 BIT(1)
#define FPGA_OVERFLOW_HI_CH8 BIT(0)

/* FPGA_OVERFLOW_LOW */
#define FPGA_OVERFLOW_LOW 0x65
#define FPGA_OVERFLOW_LOW_DEFAULT 0xff
#define FPGA_OVERFLOW_LOW_CH7 BIT(7)
#define FPGA_OVERFLOW_LOW_CH6 BIT(6)
#define FPGA_OVERFLOW_LOW_CH5 BIT(5)
#define FPGA_OVERFLOW_LOW_CH4 BIT(4)
#define FPGA_OVERFLOW_LOW_CH3 BIT(3)
#define FPGA_OVERFLOW_LOW_CH2 BIT(2)
#define FPGA_OVERFLOW_LOW_CH1 BIT(1)
#define FPGA_OVERFLOW_LOW_CH0 BIT(0)

/* FPGA_UNDERFLOW_HI */
#define FPGA_UNDERFLOW_HI 0x64
#define FPGA_UNDERFLOW_HI_DEFAULT 0xff
#define FPGA_UNDERFLOW_HI_CH15 BIT(7)
#define FPGA_UNDERFLOW_HI_CH14 BIT(6)
#define FPGA_UNDERFLOW_HI_CH13 BIT(5)
#define FPGA_UNDERFLOW_HI_CH12 BIT(4)
#define FPGA_UNDERFLOW_HI_CH11 BIT(3)
#define FPGA_UNDERFLOW_HI_CH10 BIT(2)
#define FPGA_UNDERFLOW_HI_CH9 BIT(1)
#define FPGA_UNDERFLOW_HI_CH8 BIT(0)

/* FPGA_UNDERFLOW_LOW */
#define FPGA_UNDERFLOW_LOW 0x63
#define FPGA_UNDERFLOW_LOW_DEFAULT 0xff
#define FPGA_UNDERFLOW_LOW_CH7 BIT(7)
#define FPGA_UNDERFLOW_LOW_CH6 BIT(6)
#define FPGA_UNDERFLOW_LOW_CH5 BIT(5)
#define FPGA_UNDERFLOW_LOW_CH4 BIT(4)
#define FPGA_UNDERFLOW_LOW_CH3 BIT(3)
#define FPGA_UNDERFLOW_LOW_CH2 BIT(2)
#define FPGA_UNDERFLOW_LOW_CH1 BIT(1)
#define FPGA_UNDERFLOW_LOW_CH0 BIT(0)

/* FPGA_DBG_OCCUPANCY_CMD */
#define FPGA_DBG_OCCUPANCY_CMD 0x62
#define FPGA_DBG_OCCUPANCY_CMD_MSK BIT(0)

/* FPGA_DBG_OCCUPANCY_IDX */
#define FPGA_DBG_OCCUPANCY_IDX 0x61
#define FPGA_DBG_OCCUPANCY_IDX_A_MSK GENMASK(3, 0)
#define FPGA_DBG_OCCUPANCY_IDX_B_MSK GENMASK(7, 4)

/* FPGA_DBG_OCCUPANCY_A_MAX */
#define FPGA_DBG_OCCUPANCY_A_MAX 0x60
/* FPGA_DBG_OCCUPANCY_A_MIN */
#define FPGA_DBG_OCCUPANCY_A_MIN 0x5f

/* FPGA_DBG_OCCUPANCY_B_MAX */
#define FPGA_DBG_OCCUPANCY_B_MAX 0x5e
/* FPGA_DBG_OCCUPANCY_B_MIN */
#define FPGA_DBG_OCCUPANCY_B_MIN 0x5d

/* FPGA_SYNC_ERROR */
#define FPGA_SYNC_ERROR_0 0x5c
#define FPGA_SYNC_ERROR_1 0x5b
#define FPGA_SYNC_ERROR_2 0x5a
#define FPGA_SYNC_ERROR_3 0x59

/* FPGA_*_ERROR_TRH */
#define FPGA_FREQ_ERROR_TRH 0x57
#define FPGA_SYNC_ERROR_TRH 0x56

/* FPGA_*_ERROR_TRH */
#define FPGA_PPS_PHASE_OFFSET 0x55
#define FPGA_FREQ_MONITOR_DELTA 0x54

#define FPGA_FW_VERSION 0x71

#endif /* FPGA_H_ */
