#!/bin/bash -eu

. debian/debian.env

# Ressurect old jammy:linux-riscv based config and rules.d
rsync -avc --delete "debian.riscv/config/" "${DEBIAN}/config"
rsync -avc --delete "debian.riscv/rules.d/" "${DEBIAN}/rules.d"
rsync -avc --delete "debian.riscv/control.d/generic.inclusion-list" "${DEBIAN}/control.d/generic.inclusion-list"

# Do not enforce DMESG_RESTRICT in focal
sed -i 's/CONFIG_SECURITY_DMESG_RESTRICT=y/# CONFIG_SECURITY_DMESG_RESTRICT is not set/' ${DEBIAN}/config/config.common.ubuntu
sed -i "s/CONFIG_SECURITY_DMESG_RESTRICT                  policy<{'riscv64': 'y'}>/CONFIG_SECURITY_DMESG_RESTRICT                  policy<{'riscv64': 'n'}>/" ${DEBIAN}/config/annotations

# Kasan not available on riscv64
sed -i "/^CONFIG_KASAN/d" ${DEBIAN}/config/annotations

# Drop CONFIG_DEBUG_INFO_DWARF5 because we have a toolchain too old to support
# this in focal.
sed -i "/CONFIG_DEBUG_INFO_DWARF5/d" ${DEBIAN}/config/annotations
sed -i 's/.*CONFIG_DEBUG_INFO_DWARF5.*/# CONFIG_DEBUG_INFO_DWARF5 is not set/' ${DEBIAN}/config/config.common.ubuntu

# Set CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT to y across all arches
sed -i "s/CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT .*/CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT       policy<{'amd64': 'y', 'arm64': 'y', 'armhf': 'y', 'ppc64el': 'y', 's390x': 'y'}>/" ${DEBIAN}/config/annotations

# Re-enable AUFS
#
# We are still supporting AUFS in focal, so make sure to re-enable it.
cat << EOF >> ${DEBIAN}/config/config.common.ubuntu
CONFIG_AUFS_BDEV_LOOP=y
# CONFIG_AUFS_BRANCH_MAX_1023 is not set
CONFIG_AUFS_BRANCH_MAX_127=y
# CONFIG_AUFS_BRANCH_MAX_32767 is not set
# CONFIG_AUFS_BRANCH_MAX_511 is not set
# CONFIG_AUFS_BR_FUSE is not set
CONFIG_AUFS_BR_HFSPLUS=y
# CONFIG_AUFS_BR_RAMFS is not set
# CONFIG_AUFS_DEBUG is not set
CONFIG_AUFS_DIRREN=y
CONFIG_AUFS_EXPORT=y
# CONFIG_AUFS_FHSM is not set
CONFIG_AUFS_FS=m
# CONFIG_AUFS_HNOTIFY is not set
CONFIG_AUFS_INO_T_64=y
# CONFIG_AUFS_RDU is not set
CONFIG_AUFS_SBILIST=y
# CONFIG_AUFS_SHWH is not set
CONFIG_AUFS_XATTR=y
EOF

sed -i "/^CONFIG_AUFS_FS /d" ${DEBIAN}/config/annotations
TMPFILE=$(mktemp)
cat <<EOF >${TMPFILE} || true
CONFIG_AUFS_FS                                  policy<{'riscv64': 'm'}>
CONFIG_AUFS_HNOTIFY                             policy<{'riscv64': 'n'}>
CONFIG_AUFS_EXPORT                              policy<{'riscv64': 'y'}>
CONFIG_AUFS_XATTR                               policy<{'riscv64': 'y'}>
CONFIG_AUFS_FHSM                                policy<{'riscv64': 'n'}>
CONFIG_AUFS_RDU                                 policy<{'riscv64': 'n'}>
CONFIG_AUFS_DIRREN                              policy<{'riscv64': 'y'}>
CONFIG_AUFS_SHWH                                policy<{'riscv64': 'n'}>
CONFIG_AUFS_BR_RAMFS                            policy<{'riscv64': 'n'}>
CONFIG_AUFS_BR_FUSE                             policy<{'riscv64': 'n'}>
CONFIG_AUFS_BR_HFSPLUS                          policy<{'riscv64': 'y'}>
CONFIG_AUFS_DEBUG                               policy<{'riscv64': 'n'}>
#
CONFIG_AUFS_EXPORT                              note<LP:1121699>
EOF
gawk -i inplace "/CONFIG_AUFS_FS                                  policy<{'riscv64': 'n'}>/{system(\"cat ${TMPFILE}\");next}1" ${DEBIAN}/config/annotations
rm -f ${TMPFILE}

# Override options in rules.d/hooks.mk (normally master does not have this
# file but it got added for generic annotations enforcement.
cat <<'EOD' >> ${DEBIAN}/rules.d/hooks.mk
do_libc_dev_package	= false
do_doc_package		= false
do_tools_common		= false
do_tools_host		= false

# Set inconsistent toolchain
export GCC_SUFFIX=-10
# Target
export CC=$(CROSS_COMPILE)gcc$(GCC_SUFFIX)
kmake += CC=$(CC)
EOD
